### ISSUE TITLE
Footer done but need advice 

### ISSUE THREAD

**Issue by mtubwakab** [HackYourFutureBEHomework/class2-project-bementor-group2#4]
I created the footer using the following code 

```
import React, { Component } from "react";
import styles from "/home/hyfbe16/class2-project-bementor-group2/client/src/assets/css/footer.css";

class Footer extends Component {
  render() {
  return (
      <div id="container">
        <div className="header">
          <div className="footer">
            <footer>
              <ul>
                <i className="fab fa-twitter" />
                {' '}
                <i className="fab fa-facebook-f" />
                {' '}
                <i className="fab fa-github" />
                {' '}
                <i className="" />
                {' '}® eMighty-Powerfull Coding
             </ul>
            </footer>
          </div>
        </div>
      </div>
    );
  }
}

export default Footer;
```

and the following style in footer.css: 
```
/* Style the footer */
.footer {
  background-color: #009688;
  padding: 15px;
  text-align: left;
  color: white;
  position: relative;
  }
```
-------
===> MY QUESTION: I cannot figure out 
(1) what to use instead of 
**_import styles from "/home/hyfbe16/class2-project-bementor-group2/client/src/assets/css/footer.css";_**
to make sure the style is not only stored on my computer (do I need to install an npm package to help me with the styling?
(2)how to change the font-style of                 **_<i className="" />
                {' '}® eMighty-Powerfull Coding_**
(3)how to add more space between the social media icons
(4)I need a reminder on how to share what have been done with the team
--------
===>REMARK**_@GROUP2 coworkers_** : I have changed the group name from MIGHTY to eMighty and added the 'brand emphasizer' "Powerfull Coding" please let me know  if OK with you.
-------
![screenshot 2019-03-04 02 21 04](https://user-images.githubusercontent.com/42099995/53705384-62de6e80-3e24-11e9-91f8-eb9e973e8902.png)
![screenshot 2019-03-04 02 21 30](https://user-images.githubusercontent.com/42099995/53705387-696ce600-3e24-11e9-9b96-a89ed84fa3bf.png)

![screenshot 2019-03-04 02 28 35](https://user-images.githubusercontent.com/42099995/53705516-7e964480-3e25-11e9-9fba-daa258e09b8a.png)

**Comment by archived-m** [comment]
Hey Madeleine, good work so far :)

To answer your questions

1.  You can use relative importing to make sure imports work for everyone. This is relative to the location of the file you're currently in. In this case it would be `import '../assets/css/footer.css'`
2. Changing the font-style is nothing new, you do it the same way you do in HTML. Wrap the text in a container (such as a `<span>`) and give it a class. Then set that class' `font-family` property in CSS
3. You've seen a few ways to increase spacing between elements using CSS. Play around with `margin` and `padding` to get your desired results
4. You can tag your team members like this @HackYourFutureBEHomework/class-2-group-2, or simply message them on Slack. These updates are more fit for a **pull request** though. I imagine you have your own branch, so you can create a pull request with `master` as the base branch. Request review from your teammates on it, and they'll receive an email saying that it is open.
This also saves you from having to put your code in the description, people will be able to see it in your commits in the pull request.

**Comment by Hassanalihazaraa** [comment]
@mtubwakab thats good that you made the footer but it should be in bottom

**Comment by Hassanalihazaraa** [comment]
and btw what emighty powerful coding means ? i am curious :)
